# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  macos-selfhosted:
    runs-on: [self-hosted, macOS, X64]

    steps:
      - uses: actions/checkout@v2

      - name: Run a simple test script
        run: .github/workflows/test.sh

  windows-selfhosted:
    runs-on: [self-hosted, Windows, X64]

    steps:
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a simple Windows test script
      run: .github/workflows/test.cmd

  linux-normal:
    runs-on: [Linux, x64]

    steps:
    - uses: actions/checkout@v2

    - name: Run a simple test script
      run: .github/workflows/test.sh
