# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  mixed:
    strategy:
      matrix:
        # webserver: [apache-fpm, nginx-fpm]
        webserver: [ nginx-fpm ]
        #        tests: [testcmd, testnotddevapp, testddevapp]
        tests: [ testcmd, testnotddevapp ]
        os: [ ubuntu-20.04, [ self-hosted, macos ] ]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Run a simple test script
      run: .github/workflows/test.sh

  macos-selfhosted:
    runs-on: [self-hosted, macOS, X64]

    steps:
      - uses: actions/checkout@v2

      - name: Run a simple test script
        run: .github/workflows/test.sh

  windows-selfhosted:
    runs-on: [self-hosted, Windows, X64]

    steps:
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a simple Windows test script
      run: .github/workflows/test.cmd

  linux-normal:
    runs-on: [ubuntu-20.04]

    steps:
    - uses: actions/checkout@v2

    - name: Run a simple test script
      run: .github/workflows/test.sh
